default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQLUSER", "root") %>
  password: <%= ENV.fetch("MYSQLPASSWORD", "Imtjrocks@123") %>

development:
  <<: *default
  database: <%= ENV.fetch("MYSQLDATABASE_APP", "mdoner-dashboard") %>

test:
  <<: *default
  database: crm_test

production:
  url: "<%= ENV['DATABASE_URL'] %>"