default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQLUSER", "root") %>
  password: <%= ENV.fetch("MYSQLPASSWORD", "Imtjrocks@123") %>

development:
  <<: *default
  database: <%= ENV.fetch("MYSQLDATABASE_APP", "mdoner-dashboard") %>

#  url: <%#= ENV["DATABASE_URL"] %>
#  port: <%#= ENV.fetch("MYSQLPORT", 35928) %>
#  host: <%#= ENV.fetch("MYSQLHOST", "localhost") %>

test:
  <<: *default
  database: crm_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>