default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "Imtjrocks@123") %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: <%= ENV.fetch("MYSQL__DATABASE_APP", "mdoner-dashboard") %>

test:
  <<: *default
  database: chhatisgarh_test

# production:
#   <<: *default
#   username: <%= ENV.fetch("MYSQL_USER", "root") %>
#   password: <%= ENV.fetch("MYSQL_PASSWORD", "Imtjrocks@123") %>
#   host: <%= ENV["MYSQL_HOST"] %>
#   port: <%= ENV["MYSQL_PORT"] %>
#   database: <%= ENV["MYSQL_DATABASE"] %>
production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>